name: deploy-user-service

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11.0.x' ]
    steps:
    - uses: actions/checkout@v1
    - name: Setup java
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
        architecture: x64
    - name: build artifact
      run: ./gradlew build
    - name: build docker image
      run: docker build . --file ./Dockerfile --tag dokku/user-service:v${{ github.sha }}
    - name: zip deployable
      run: docker save dokku/user-service:v${{ github.sha }} | bzip2 > ${{ github.sha }}.tar.bz
    - uses: appleboy/scp-action@master
      name: scp files to remote host
      env:
        USERNAME: ${{ secrets.GEEKSVEN_USERNAME }}
        PASSWORD: ${{ secrets.GEEKSVEN_PASSWORD }}
        HOST: geeksven.com
        SOURCE: "*.tar.bz"
        TARGET: /home/geeksven
    - uses: appleboy/ssh-action@master
      name: docker load image
      env:
        USERNAME: ${{ secrets.GEEKSVEN_USERNAME }}
        PASSWORD: ${{ secrets.GEEKSVEN_PASSWORD }}
        HOST: geeksven.com
        GITHUB_SHA: ${{github.sha}}
        SCRIPT: bunzip2 ${{ github.sha }}.tar.bz && docker load --input=${{ github.sha }}.tar
    - uses: appleboy/ssh-action@master
      name: dokku deploy
      env:
        USERNAME: ${{ secrets.GEEKSVEN_USERNAME }}
        PASSWORD: ${{ secrets.GEEKSVEN_PASSWORD }}
        HOST: geeksven.com
        SCRIPT: dokku tags:create user-service previous; dokku tags:deploy user-service v${{ github.sha }}